name: Amul Product Check

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:  # allows manual trigger

jobs:
  run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Maven Tests
        run: mvn test
